#+TITLE: let us formalize something.

* companies act

** 161 (1)

Approval of company required for issue of shares by directors
161.—(1) Notwithstanding anything in a company’s constitution,
the directors shall not, without the prior approval of the company in
general meeting, exercise any power of the company to issue shares.
[10/74; 15/84] [Act 36 of 2014 wef 03/01/2016]

** The Code
#+BEGIN_SRC

#+END_SRC

** 161 (2)
Approval for the purposes of this section may be confined to a particular exercise of that power or may apply to the exercise of that power generally; and any such approval may be unconditional or subject to conditions.

** 161 (3)
Any approval for the purposes of this section shall continue in force until —
(a) the conclusion of the annual general meeting commencing next after the date on which the approval was given; or
(b) the expiration of the period within which the next annual general meeting after that date is required by law to be held,
whichever is the earlier; but any approval may be previously revoked or varied by the company in general meeting.

** 161 (4)
The directors may issue shares notwithstanding that an approval for the purposes of this section has ceased to be in force if the shares are issued in pursuance of an offer, agreement or option made or granted by them while the approval was in force and they were authorised by the approval to make or grant an offer, agreement or option which would or might require shares to be issued after the
expiration of the approval.

** 161 (5)
Section 186 shall apply to anyr esolution whereby an approval is given for the purposes of this section.

** 161 (6)
Any issue of shares made by a company in contravention of this section shall be void and consideration given for the shares shall be recoverable accordingly.

** 161 (7)
Any director who knowingly contravenes, or permits or authorises the contravention of, this section with respect to any issue of shares shall be liable to compensate the company and the person to whom the shares were issued for any loss, damages or costs which the company or that person may have sustained or incurred thereby; but no proceedings to recover any such loss, damages or costs shall be commenced after the expiration of 2 years from the date of the issue.


* securities and futures act

** Issue or transfer of securities for no consideration

*** 272.—(1)
Subdivisions (2) and (3) of this Division (other than section 257) shall not apply to an offer of shares or debentures of an entity if no consideration is or will be given for the issue or transfer of the shares or debentures.

*** (2)
Subdivisions (2) and (3) of this Division (other than section 257) shall not apply to an offer of units of shares or debentures of an entity if —

**** (a)
no consideration is or will be given for the issue or transfer of the units of shares or debentures; and

**** (b)
no consideration is or will be given for the underlying shares or debentures on the exercise or conversion of the units of shares or debentures.

** Small offers

*** 272A.—(1)

Subdivisions (2) and (3) of this Division (other than section 257) shall not apply to personal offers of securities of an entity by a person if —

**** (a)
the total amount raised by the person from such offers within any period of 12 months does not exceed —

***** (i)
$5 million (or its equivalent in a foreign currency); or

***** (ii)
such other amount as may be prescribed by the Authority in substitution for the amount specified in sub-paragraph (i);

**** (b)
in respect of each offer, the person making the offer gives the person to whom he makes the offer —

***** (i)
the following statement in writing:
“This offer is made in reliance on the exemption under section 272A(1) of the Securities and Futures Act. It is not made in or accompanied by a prospectus that is registered by the Monetary Authority of Singapore.”; and

***** (ii)
a notification in writing that the securities to which the offer (referred to in this sub-paragraph as the initial offer) relates shall not be subsequently sold to any person, unless the offer resulting in such subsequent sale is made —

****** (A)
in compliance with Subdivisions (2) and (3) of this Division;

****** (B)
in reliance on subsection (8)(c) or any other exemption under any provision of this Subdivision (other than this subsection); or

****** (C)
where at least 6 months have elapsed from the date the securities were acquired under the initial offer, in reliance on the exemption under this subsection;

**** (c)
none of the offers is accompanied by an advertisement making an offer or calling attention to the offer or intended offer;
[2/2009 wef 29/07/2009]

**** (d)
no selling or promotional expenses are paid or incurred in connection with each offer other than those incurred for administrative or professional services, or by way of commission or fee for services rendered by —

***** (i)
the holder of a capital markets services licence to deal in securities;

***** (ii)
an exempt person in respect of dealing in securities; or

***** (iii)
a person who is licensed, approved, authorised or otherwise regulated under the laws, codes or other requirements of any foreign jurisdiction in respect of dealing in securities, or who is exempted therefrom in respect of such dealing; and

[2/2009 wef 29/07/2009]
[1/2005]

**** (e)
no prospectus in respect of any of the offers has been registered by the Authority or, where a prospectus has been registered —

***** (i)
the prospectus has expired pursuant to section 250; or

***** (ii)
the person making the offer has before making the offer informed the Authority by notice in writing of its intent to make the offer in reliance on the exemption under this subsection.

*** (2)
For the purposes of subsection (1)(b), where any notice, circular, material, publication or other document is issued in connection with the offer, the person making the offer is deemed to have given the statement and notification to the person to whom he makes the offer in accordance with that provision if such statement or notification is contained in the first page of that notice, circular, material, publication or document.
[1/2005]

*** (3)
For the purposes of subsection (1), a personal offer of securities is one that —

**** (a)
may be accepted only by the person to whom it is made; and

**** (b)
is made to a person who is likely to be interested in that offer, having regard to —

***** (i)
any previous contact before the date of the offer between the person making the offer and that person;

***** (ii)
any previous professional or other connection established before that date between the person making the offer and that person; or

***** (iii)
any previous indication (whether through statements made or actions carried out) before that date by that person that indicate to —

****** (A)
the person making the offer;

****** (B)
the holder of a capital markets services licence to deal in securities;

****** (C)
an exempt person in respect of dealing in securities;

****** (D)
a person licensed under the Financial Advisers Act (Cap. 110) in respect of the provision of financial advisory services concerning investment products;

****** (E)
an exempt financial adviser as defined in section 2(1) of the Financial Advisers Act; or

****** (F)
a person who is licensed, approved, authorised or otherwise regulated under the laws, codes or other requirements of any foreign jurisdiction in respect of dealing in securities or the provision of financial advisory services concerning investment products, or who is exempted therefrom in respect of such dealing or the provision of such services,
that he is interested in offers of that kind.
[1/2005]

*** (4)
In determining the amount raised by an offer, the following shall be included:

**** (a)
the amount payable for the securities at the time they are allotted, issued or sold;

**** (b)
if the securities are issued partly-paid, any amount payable at a future time if a call is made;

**** (c)
if the securities carry a right (by whatever name called) to be converted into other securities or to acquire other securities, any amount payable on the exercise of the right to convert them into, or to acquire, other securities.
[1/2005]

*** (5)
In determining whether the amount raised by a person from offers within a period of 12 months exceeds the applicable amount specified in subsection (1)(a), each amount raised —

**** (a)
by that person from any offer of securities issued by the same entity; or

**** (b)
by that person or another person from any offer of securities of an entity, units or derivatives of units in a business trust, or units in a collective investment scheme, which is a closely related offer,
if any, within that period in reliance on the exemption under subsection (1), section 282V(1) or 302B(1) shall be included.
[1/2005]

*** (6)
Whether an offer is a closely related offer under subsection (5) shall be determined by considering such factors as the Authority may prescribe.
[1/2005]

*** (7)
For the purpose of this section, an offer of securities made by a person acting as an agent of another person shall be treated as an offer made by that other person.
[1/2005]

*** (8)
Where securities acquired through an offer made in reliance on the exemption under subsection (1) (referred to in this subsection as an initial offer) are subsequently sold by the person who acquired the securities to another person, Subdivisions (2) and (3) of this Division shall apply to the offer from the first-mentioned person to the second-mentioned person which resulted in that sale, unless —

**** (a)
such offer is made in reliance on an exemption under any provision of this Subdivision (other than this section);

**** (b)
such offer is made in reliance on an exemption under subsection (1) and at least 6 months have elapsed from the date the securities were acquired under the initial offer; or

**** (c)
such offer is one —

***** (i)
that may be accepted only by the person to whom it is made;

***** (ii)
that is made to a person who is likely to be interested in the offer having regard to —

****** (A)
any previous contact before the date of the offer between the person making the initial offer and that person;

****** (B)
any previous professional or other connection established before that date between the person making the initial offer and that person; or

****** (C)
any previous indication (whether through statements made or actions carried out) before that date by that person that indicate to —

******* (CA)
the person making the initial offer;

******* (CB)
the holder of a capital markets services licence to deal in securities;

******* (CC)
an exempt person in respect of dealing in securities;

******* (CD)
a person licensed under the Financial Advisers Act (Cap. 110) in respect of the provision of financial advisory services concerning investment products;

******* (CE)
an exempt financial adviser as defined in section 2(1) of the Financial Advisers Act; or

******* (CF)
a person who is licensed, approved, authorised or otherwise regulated under the laws, codes or other requirements of any foreign jurisdiction in respect of dealing in securities or the provision of financial advisory services concerning investment products, or who is exempted therefrom in respect of such dealing or the provision of such services,
that he is interested in offers of that kind;

***** (iii)
in respect of which the first-mentioned person has given the second-mentioned person —

****** (A)
the following statement in writing:
“This offer is made in reliance on the exemption under section 272A(8)(c) of the Securities and Futures Act. It is not made in or accompanied by a prospectus that is registered by the Monetary Authority of Singapore.”; and

****** (B)
a notification in writing that the securities being offered shall not be subsequently sold to any person unless the offer resulting in such subsequent sale is made —

******* (BA)
in compliance with Subdivisions (2) and (3) of this Division;

******* (BB)
in reliance on this subsection or any other exemption under any provision of this Subdivision (other than subsection (1)); or

******* (BC)
where at least 6 months have elapsed from the date the securities were acquired under the initial offer, in reliance on the exemption under subsection (1);

***** (iv)
that is not accompanied by an advertisement making an offer or calling attention to the offer or intended offer; and

***** (v)
in respect of which no selling or promotional expenses are paid or incurred in connection with the offer other than those incurred for administrative or professional services, or by way of commission or fee for services rendered by —

***** (A)
the holder of a capital markets services licence to deal in securities;

***** (B)
an exempt person in respect of dealing in securities; or

***** (C)
a person who is licensed, approved, authorised or otherwise regulated under the laws, codes or other requirements of any foreign jurisdiction in respect of dealing in securities, or who is exempted therefrom in respect of such dealing.
[1/2005]

**** (9)
Subsection (2) shall apply, with the necessary modifications, in relation to the statement and notification referred to in subsection (8)(c)(iii).
[1/2005]

**** (10)
In subsections (1)(c) and (8)(c)(iv), “advertisement” means —

***** (a)
a written or printed communication;

***** (b)
a communication by radio, television or other medium of communication; or

***** (c)
a communication by means of a recorded telephone message,
that is published in connection with an offer of securities, but does not include —

****** (i)
a document —

******* (A)
purporting to describe the securities being offered, or the business and affairs of the person making the offer, the issuer or, where applicable, the underlying entity; and

******* (B)
purporting to have been prepared for delivery to and review by persons to whom the offer is made so as to assist them in making an investment decision in respect of the securities being offered;

****** (ii)
a publication which consists solely of a disclosure, notice or report required under this Act, or any listing rules or other requirements of a securities exchange, futures exchange or overseas securities exchange, which is made by any person; or
[2/2009 wef 29/07/2009]

****** (iii)
a publication which consists solely of a notice or report of a general meeting or proposed general meeting of the person making the offer, the issuer, the underlying entity or any entity, or a presentation of oral or written material on matters so contained in the notice or report at the general meeting.
[1/2005]

**** (11)  In subsection (10)(i)(A), the reference to the affairs of the person making the offer, the issuer or, where applicable, the underlying entity shall —
(a)
in the case where the person making the offer, the issuer or the underlying entity is a corporation, be construed as including a reference to the matters referred to in section 2(2); and
(b)
in any other case, be construed as referring to such matters as may be prescribed by the Authority.
[1/2005]






** Private placement
272B.—(1)  Subdivisions (2) and (3) of this Division (other than section 257) shall not apply to offers of securities of an entity that are made by a person if —
(a)
the offers are made to no more than 50 persons within any period of 12 months;
(b)
none of the offers is accompanied by an advertisement making an offer or calling attention to the offer or intended offer;
[2/2009 wef 29/07/2009]
(c)
no selling or promotional expenses are paid or incurred in connection with each offer other than those incurred for administrative or professional services, or by way of commission or fee for services rendered by —
(i)
the holder of a capital markets services licence to deal in securities;
(ii)
an exempt person in respect of dealing in securities; or
(iii)
a person who is licensed, approved, authorised or otherwise regulated under the laws, codes or other requirements of any foreign jurisdiction in respect of dealing in securities, or who is exempted therefrom in respect of such dealing; and
[2/2009 wef 29/07/2009]
[1/2005]
(d)
no prospectus in respect of any of the offers has been registered by the Authority or, where a prospectus has been registered —
(i)
the prospectus has expired pursuant to section 250; or
(ii)
the person making the offer has before making the offer —
(A)
informed the Authority by notice in writing of its intent to make the offer in reliance on the exemption under this subsection; and
(B)
taken reasonable steps to inform in writing the person to whom the offer is made that the offer is made in reliance on the exemption under this subsection.
(2)  The Authority may prescribe such other number of persons in substitution for the number specified in subsection (1)(a).
[1/2005]
(3)  In determining whether offers of securities by a person are made to no more than the applicable number of persons specified in subsection (1)(a) within a period of 12 months, each person to whom —
(a)
an offer of securities issued by the same entity is made by the first-mentioned person; or
(b)
an offer of securities of an entity, units or derivatives of units in a business trust, or units in a collective investment scheme, is made by the first-mentioned person or another person where such offer is a closely related offer,
if any, within that period in reliance on the exemption under this section, section 282W or 302C shall be included.
[1/2005]
(4)  Whether an offer is a closely related offer under subsection (3) shall be determined by considering such factors as the Authority may prescribe.
[1/2005]
(5)  For the purposes of subsection (1) —
(a)
an offer of securities to an entity or to a trustee shall be treated as an offer to a single person, provided that the entity or trust is not formed primarily for the purpose of acquiring the securities which are the subject of the offer;
(b)
an offer of securities to an entity or to a trustee shall be treated as an offer to the equity owners, partners or members of that entity, or to the beneficiaries of the trust, as the case may be, if the entity or trust is formed primarily for the purpose of acquiring the securities which are the subject of the offer;
(c)
an offer of securities to 2 or more persons who will own the securities acquired as joint owners shall be treated as an offer to a single person;
(d)
an offer of securities to a person acting on behalf of another person (whether as an agent or otherwise) shall be treated as an offer made to that other person;
(e)
offers of securities made by a person as an agent of another person shall be treated as offers made by that other person;
(f)
where an offer is made to a person with a view to another person acquiring an interest in those securities by virtue of section 4, only the second-mentioned person shall be counted for the purposes of determining whether offers of the securities are made to no more than the applicable number of persons specified in subsection (1)(a); and
(g)
where —
(i)
an offer of securities is made to a person in reliance on the exemption under subsection (1) with a view to those securities being subsequently offered for sale to another person; and
(ii)
that subsequent offer —
(A)
is not made in reliance on an exemption under any provision of this Subdivision; or
(B)
is made in reliance on an exemption under subsection (1) or section 280,
both persons shall be counted for the purposes of determining whether offers of the securities are made to no more than the applicable number of persons specified in subsection (1)(a).
[1/2005]
(6)  In subsection (1)(b), “advertisement” has the same meaning as in section 272A(10).
